name: GitHub Actions

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Setup PHP
        uses: actions/checkout@v3
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: files.000webhost.com:21
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_KEY }}